<?php
return[
    'app\models\ar\TravelPackageSearch' => 'travelPackage',
    'app\models\ar\TravelPackage' => [
        'tripPackageId' => 'id',
        'agentDetail' => 'company',
        'agentId' => 'company_id',
        'agentName' => 'company.name',
        'agentLogoUrl' => 'company.photoUrl',
        'packageName' => 'name',
        'promotionalText' => 'promo',
        'description',
        'days',
        'nights',
        'minimumNumberOfTraveler' => 'participantMin',
        'maximumNumberOfTraveler' => 'participantMax',
        'price',
        'startingPrice',
        'packagePrices' => 'allPrices',
        'packageSchedules',
        'photos' => 'pictures',
        'tags' => 'xTags',
        'themes' => 'xThemes',
        'reviews' => 'reviewList',
        'comments' => 'commentList',
        'commentCount' => 'agregate.comments',
        'reviewCount' => 'agregate.reviews',
        'rating' => 'agregate.rating_item',
        'viewCount' => 'agregate.views',
    ],
    'app\models\ar\Picture' => [
        'url' => 'imageUrl'
    ],
    'app\models\ar\Company' => [
        'id',
        'name',
        'address',
        'logoUrl' => 'photoUrl',
        'description',
    ],
    'app\models\ar\PackageSchedule' => [
        'id',
        'item_id',
        'isMeetingPoint',
        'day' => 'dayStart',
        'time_start' => 'timeStart',
        'description',
        'packageItem',
        'pictures',
    ],
    'app\models\ar\PackageItem' => [
        'id',
        'name',
        'item_type' => 'nmType',
        'location_name' => 'location',
        'city',
        'region',
        'country',
        'latitude',
        'longitude',
        'pictures'
    ],
    // featured
    'app\models\ar\Featured' => [
        'name',
        'description',
        'imageUrl',
        'params',
        'nameType',
    ],
    // transaction
    'app\models\ar\Transaction' => [
        'id',
        'travelingDate' => 'date',
        'user_id',
        'number',
        'status',
        'statusText' => 'nmStatus',
        'amount',
        'participant' => 'participant',
        'travelPackage' => 'travelPackage',
        'invoice',
        'packageReview'
    ],
    'app\models\ar\Invoice' => [
        'id',
        'date',
        'number',
        'name',
        'email',
        'phone',
        'status',
        'amount',
        'unique_amount',
        'payment_method' => 'method',
        'payment_method_name' => 'paymentMethod.value',
        'expireIn'
    ],
    'app\models\form\Order' => [
        'travelPackage' => 'transaction.travelPackage',
        'transaction',
        'invoice',
    ],
    'app\models\lookup\PaymentMethod' => [
        'code',
        'payment_method',
        'description',
        'expiry_after_calculate_price' => 'expire',
        'available',
        'description_url',
        'icon_url'
    ],
];
